# Generated by Django 4.0.4 on 2022-05-14 10:00

from django.db import migrations, models
import podomarket.validators


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0005_user_profile_pic_alter_post_image2_alter_post_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=40, validators=[podomarket.validators.validate_no_special_characters]),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(max_length=20, validators=[podomarket.validators.validate_no_special_characters]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 사용중인 닉네임입니다.'}, max_length=15, unique=True, validators=[podomarket.validators.validate_no_special_characters]),
        ),
    ]
